# -*- coding: utf-8 -*-
"""zigzag.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n3D4QV-yFgVBJSm-MefMQijQvjO4yPGF
"""

import matplotlib.pyplot as plt

x=[0,5,10,15,20,25,30]
y=[0,5,0,5,0,5,0]
plt.plot(x,y)
plt.title('zigzag curve')
plt.axis('off')
plt.show()

